name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [1, 2, 3]
    steps:
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - run: |
          echo "URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.run_id: ${{ github.run_id }}"
          echo "github.job: ${{ github.job }}"
          echo "job.container.id: ${{ job.container.id }}"
